#!/bin/sh

set -e

if [ "$1" = "upgrade" ] ; then
    if [ -d /run/systemd/system ]; then
        systemctl stop vmailmgrd.service || true
    fi
    if [ -f /etc/init.d/vmailmgrd ]; then
        rm -f /etc/init.d/vmailmgrd || true
    fi
fi

