#!/usr/bin/env bash

target_script='/usr/bin/vcommand'
original_script="${target_script}_original"

args=$@
ppid=$PPID
cmdline=`cat /proc/$ppid/cmdline | tr "\0" ' '`
user=`whoami`

log="parent_id: \"${ppid}\" parent_cmdline: \"${cmdline}\" target: \"${target_script}\" user: \"${user}\""
logger -t vmail_audit $log

$original_script $args
